const collectionArr = [
  "Alarm Clocks",
  "Antique Furniture",
  "Antique Weapons",
  "Apothecary Jars",
  "Arrowheads",
  "Arrows",
  "Ashtrays",
  "Autographs",
  "Automobiles",
  "Axes and Hatchets",
  "Back Scratchers",
  "Badges (law, firemen, etc.)",
  "Belt Buckles",
  "Birdhouses",
  "Blown Glass Animals and Figurines",
  "Blueprints",
  "Books",
  "Bookends",
  "Calculators",
  "Calendars – Vintage",
  "Cameras",
  "Candles",
  "Candlesticks",
  "Canes or Walking Sticks",
  "Cars",
  "Carved Decoupage Ostrich, Porcelain, and Faberge Eggs",
  "Cash Registers",
  "Cassette Tapes",
  "Christmas Ornaments and Lights",
  "Cigar Boxes",
  "Cigarette Cases",
  "Clocks",
  "Coffee Mugs",
  "College Pennants",
  "Comic Books",
  "Compasses",
  "Computers",
  "Corkscrews",
  "Correspondence from Famous People",
  "Crate Labels",
  "Decorative Tiles",
  "Decorative Wall Outlet Covers",
  "Dentistry or Medical Tools",
  "Depression Glass",
  "Dolls",
  "Door Knockers",
  "Drive-in Movie Theatre Speakers",
  "Duck Calls and Decoys",
  "Dukes of Hazzard Memorabilia",
  "Dust Jackets from Books",
  "Election Buttons",
  "Elvis (or another entertainer) Memorabilia",
  "Fans – Handheld",
  "Fishing Lures, Poles, and Tackle",
  "Flags",
  "Guitar Picks",
  "Guitars",
  "Gumball Machines",
  "Guns – Collectible",
  "Halloween Memorabilia",
  "Harmonicas",
  "Hatpins",
  "Hats",
  "Hood Ornaments",
  "Hummel Figurines",
  "Ice Skates",
  "Inkwells",
  "Japanese Warrior Dolls",
  "Jigsaw Puzzles",
  "Journals Kept by Famous People",
  "Knives",
  "Kool-Aid Memorabilia",
  "Legos",
  "Letter Openers",
  "Lithographs",
  "Locks",
  "Lunchboxes",
  "Magazines",
  "Magnifying Glasses",
  "Mandolins",
  "Masks",
  "Mason jars",
  "Medals",
  "Meteorites",
  "Microscopes",
  "Milk Glass",
  "Mirrors",
  "Mobile Phones",
  "Model Planes",
  "Model Railroads",
  "Model Ships",
  "Mortars and pestles",
  "Motorcycles",
  "Movie and TV Scripts",
  "Movie Posters",
  "Native American Artefacts and Jewellery",
  "Newspapers",
  "Nutcrackers",
  "Old Tools",
  "Paperweights",
  "Photographs",
  "Picture Frames",
  "Pinball Machines",
  "Plants – House or Garden",
  "Porcelain Dolls",
  "Pots, Old Pans, and Cauldrons",
  "Purses",
  "Sheet Music",
  "Shoes",
  "Signs",
  "Silverwares",
  "Skateboards",
  "Sneakers",
  "Snow Globes",
  "Snuff Boxes",
  "Spectacles or Reading Glasses",
  "Stock Certificates",
  "Street Signs",
  "Sundials",
  "Swords (antique)",
  "Tea Cups with Saucers",
  "Telescopes",
  "Toys (antique or vintage)",
  "Troll Dolls (from the ’70s)",
  "Trophies",
  "Vintage Valentines",
  "Wall Sconces",
  "Wallets",
  "Water Goblets",
  "Watermelon (or any other fruit) Collectibles",
  "Weathervanes",
  "Wedding Dresses or Vintage Clothing",
  "Whisky",
  "Whistles",
  "Wicker Furniture",
  "Wind Chimes",
  "Wolf or Other Animal Figurines",
  "Wrappers",
  "Wreaths",
  "Wristbands",
  "Yo-yos",
  "Zippers",
  "Zippo Lighters",
];

export default collectionArr;
